export const FETCH_RECOMMENDATIONS_REQUEST = 'FETCH_RECOMMENDATIONS_REQUEST'
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS'
export const FETCH_RECOMMENDATIONS_FAILURE = 'FETCH_RECOMMENDATIONS_FAILURE'
export const RECOMMENDATIONS_CLEAR = 'RECOMMENDATIONS_CLEAR'

export const getRecommendations = () => ({
  type: FETCH_RECOMMENDATIONS_REQUEST
})