export const FETCH_RECOMMENDATIONS_INITIATED = 'FETCH_RECOMMENDATIONS_INITIATED'
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS'
export const FETCH_RECOMMENDATIONS_FAILED = 'FETCH_RECOMMENDATIONS_FAILED'
export const RECOMMENDATIONS_CLEAR = 'RECOMMENDATIONS_CLEAR'

export const getRecommendations = () => ({
  type: FETCH_RECOMMENDATIONS_INITIATED
})
